kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  commands:
  - go test ./...
  # TODO: uncomment after fix panic: sql: register called twice for driver "test log sql open" driver name
  # - go test -v -race -count=10 ./...
  - go test -v -race ./...
  - go build ./...
